// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PapayaServiceClient is the client API for PapayaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PapayaServiceClient interface {
	Predict(ctx context.Context, in *PredictionRequest, opts ...grpc.CallOption) (*PredictionResponse, error)
}

type papayaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPapayaServiceClient(cc grpc.ClientConnInterface) PapayaServiceClient {
	return &papayaServiceClient{cc}
}

func (c *papayaServiceClient) Predict(ctx context.Context, in *PredictionRequest, opts ...grpc.CallOption) (*PredictionResponse, error) {
	out := new(PredictionResponse)
	err := c.cc.Invoke(ctx, "/PapayaService/Predict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PapayaServiceServer is the server API for PapayaService service.
// All implementations must embed UnimplementedPapayaServiceServer
// for forward compatibility
type PapayaServiceServer interface {
	Predict(context.Context, *PredictionRequest) (*PredictionResponse, error)
	mustEmbedUnimplementedPapayaServiceServer()
}

// UnimplementedPapayaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPapayaServiceServer struct {
}

func (UnimplementedPapayaServiceServer) Predict(context.Context, *PredictionRequest) (*PredictionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedPapayaServiceServer) mustEmbedUnimplementedPapayaServiceServer() {}

// UnsafePapayaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PapayaServiceServer will
// result in compilation errors.
type UnsafePapayaServiceServer interface {
	mustEmbedUnimplementedPapayaServiceServer()
}

func RegisterPapayaServiceServer(s grpc.ServiceRegistrar, srv PapayaServiceServer) {
	s.RegisterService(&PapayaService_ServiceDesc, srv)
}

func _PapayaService_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PapayaServiceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PapayaService/Predict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PapayaServiceServer).Predict(ctx, req.(*PredictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PapayaService_ServiceDesc is the grpc.ServiceDesc for PapayaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PapayaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PapayaService",
	HandlerType: (*PapayaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _PapayaService_Predict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "papaya-service.proto",
}
